# Generated by Django 2.2.28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import esp.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dbmail', '0010_textofemail_messagerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('announcement', 'Announcement'), ('registration', 'Registration'), ('schedule', 'Schedule'), ('reminder', 'Reminder'), ('newsletter', 'Newsletter'), ('custom', 'Custom')], default='custom', max_length=32)),
                ('gjs_data', models.TextField(help_text='GrapesJS editor JSON (components + styles)')),
                ('html_content', models.TextField(help_text='Compiled HTML output from MJML')),
                ('mjml_content', models.TextField(blank=True, default='', help_text='Raw MJML markup (for reference)')),
                ('thumbnail', models.TextField(blank=True, default='', help_text='Base64 data URI for template card preview')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive templates are hidden from the selector but not deleted')),
                ('creator', esp.db.fields.AjaxForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
