# Generated by Django 2.2.28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmail', '0011_emailtemplate'),
        ('dbmail', '0012_auto_20260224_0619'),
    ]

    operations = [
    ]
